import vazirFont from "@/constants/localFonts";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "../../globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "صفحه ادمین",
  description: "Generated by create next app",
};

const queryClinet = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        suppressHydrationWarning={true}
        className={`${vazirFont.variable} font-sans`}
      >
        <QueryClientProvider client={queryClinet}>
          <Toaster />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
