"use client";

import ",./globals.css";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "دیجی شاپ / خانه",
  description: "Generated by create next app",
};

const queryClinet = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={inter.className}>
        <QueryClientProvider client={queryClinet}>
          <Toaster />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
